######################################################################
# @author      : Enno Boland (mail@eboland.de)
# @file        : Makefile
# @created     : Wednesday Jun 21, 2023 10:40:47 CEST
######################################################################

all: main
	./main

main:
	go build main.go

clean:
	rm -f main
