---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - go-example.aaaaaaah.dev
  resources:
  - secrettemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - go-example.aaaaaaah.dev
  resources:
  - secrettemplates/finalizers
  verbs:
  - update
- apiGroups:
  - go-example.aaaaaaah.dev
  resources:
  - secrettemplates/status
  verbs:
  - get
  - patch
  - update
