# permissions for end users to edit secrettemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secrettemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-sdk-operator
    app.kubernetes.io/part-of: go-sdk-operator
    app.kubernetes.io/managed-by: kustomize
  name: secrettemplate-editor-role
rules:
- apiGroups:
  - go-example.aaaaaaah.dev
  resources:
  - secrettemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - go-example.aaaaaaah.dev
  resources:
  - secrettemplates/status
  verbs:
  - get
